# Copyright (C) 2018-2022 Intel Corporation
#
# SPDX-License-Identifier: MIT

services:
  cvat_server:
    labels:
      - traefik.http.routers.cvat.entrypoints=websecure
      - traefik.http.routers.cvat.tls.certresolver=lets-encrypt
      - 'traefik.http.middlewares.icarewounds_ips_whitelist.ipwhitelist.sourcerange=127.0.0.1/32, 193.144.32.66/30, 77.253.192.219, 178.43.105.209, 192.168.18.10'
      - 'traefik.http.routers.cvat.middlewares=icarewounds_ips_whitelist'

  cvat_ui:
    labels:
      - traefik.http.routers.cvat-ui.entrypoints=websecure
      - traefik.http.routers.cvat-ui.tls.certresolver=lets-encrypt
      - 'traefik.http.routers.cvat-ui.middlewares=icarewounds_ips_whitelist'

  traefik:
    image: traefik:v2.9
    container_name: traefik
    environment:
      TRAEFIK_ENTRYPOINTS_web_ADDRESS: :80
      TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_TO: websecure
      TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: https
      TRAEFIK_ENTRYPOINTS_websecure_ADDRESS: :443
      TRAEFIK_CERTIFICATESRESOLVERS_lets-encrypt_ACME_EMAIL: '${ACME_EMAIL:?Please set the ACME_EMAIL env variable}'
      TRAEFIK_CERTIFICATESRESOLVERS_lets-encrypt_ACME_TLSCHALLENGE: 'true'
      TRAEFIK_CERTIFICATESRESOLVERS_lets-encrypt_ACME_STORAGE: /letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - cvat_letsencrypt:/letsencrypt

volumes:
  cvat_letsencrypt:
